### ISSUE TITLE
IAM User Delete

### ISSUE THREAD

**Issue by SendDerek** [BourgoisMickael/aws-console-autofill-delete#2]
STRs:

1.  Create a new user in IAM
2. Select user in user list using checkbox and click "Delete"

Expected results:  The delete confirmation text field is filled out automatically
Actual results:  It is blank

![Screenshot 2023-08-23 at 11 33 04 AM](https://github.com/BourgoisMickael/aws-console-autofill-delete/assets/469263/81dccf58-00d6-4f30-b683-2d95f8664de3)

BTW: I love the work you've done with this plugin.  Thank you!

**Comment by BourgoisMickael** [comment]
Thanks for letting me know, aws keeps updating their UI, it's not easy to keep up.

It has been fixed in version 2.10
